### ISSUE TITLE
Linux: crash when applying settings if file doesn't exist

### ISSUE THREAD

**Issue by Squaduck** [StefanLobbenmeier/yt-dlp-compose#98]
When you change the settings for the first time and try to apply it, the application crashes.
This can be worked around by creating the file at the path given by the error box with the contents `{}` to make it valid JSON

**Comment by StefanLobbenmeier** [comment]
Thanks for the report - did you have to create just the file or also the folder? It might just be a missing mkdirs -p call from my application

**Comment by Squaduck** [comment]
I also made the folder. I forget if I tried it with just the folder before making the file.
I can check later if needed.

**Comment by StefanLobbenmeier** [comment]
I see, many thanks for confirming 😄 

I also figured out the reason this happens on Linux but not macOS or Windows, I use this library to follow the os conventions for data directories and config directories:

https://github.com/dirs-dev/directories-jvm/blob/b76e3606c01e6f55b354e32a30e85ee6b9f815ca/src/main/java/dev/dirs/BaseDirectories.java#L78


On macOS and windows, the folders are the same for data and settings, so the folder is already there because dependencies have been downloaded there, on Linux its a different folder, so it did not exist yet.
